import { ref } from "vue";

const STORAGE_KEY = "dynamic-form-ui-language";
const DEFAULT_LANGUAGE = "zh-CN";

const MESSAGES = {
  "zh-CN": {
    "common.chinese": "中文",
    "common.english": "English",
    "common.cancel": "取消",
    "common.close": "关闭",
    "common.confirm": "确认",
    "common.select": "请选择",
    "common.refresh": "刷新",
    "common.save": "保存",
    "common.loading": "加载中...",
    "common.noData": "暂无数据",
    "common.backToForms": "返回表单列表",
    "common.logout": "退出登录",
    "common.changePassword": "修改密码",
    "common.relogin": "重新登录",
    "route.users": "账号管理",
    "route.teams": "团队管理",
    "route.forms": "表单管理",
    "route.formDesigner": "表格设计界面",
    "route.formFill": "表单填写",
    "route.history": "历史表单",
    "route.documents": "文档中心",
    "route.bilingualEditor": "编辑双语简表",
    "layout.brandTitle": "动态表单协同",
    "layout.brandSubtitle": "管理后台",
    "layout.expandSidebar": "展开侧边栏",
    "layout.collapseSidebar": "收起侧边栏",
    "layout.logoutConfirmTitle": "确认退出",
    "layout.logoutConfirmBody": "确认退出当前账号吗？退出后将返回登录页。",
    "layout.logoutConfirmAction": "确认退出",
    "layout.passwordDialogTitle": "修改密码",
    "layout.passwordOld": "旧密码",
    "layout.passwordNew": "新密码",
    "layout.passwordConfirm": "确认新密码",
    "layout.passwordOldPlaceholder": "请输入旧密码",
    "layout.passwordNewPlaceholder": "请输入新密码",
    "layout.passwordConfirmPlaceholder": "请再次输入新密码",
    "layout.passwordSubmit": "确认修改",
    "layout.passwordSubmitting": "提交中...",
    "layout.passwordChangeSuccess": "密码修改成功，请重新登录。",
    "layout.passwordOldRequired": "旧密码不能为空",
    "layout.passwordNewRequired": "新密码不能为空，请输入6-18位并包含字母、数字、符号",
    "layout.passwordNewInvalid": "新密码格式错误，请输入6-18位并包含字母、数字、符号",
    "layout.passwordConfirmRequired": "请再次输入新密码",
    "layout.passwordConfirmMismatch": "两次输入的新密码不一致",
    "layout.sessionExpiredTitle": "登录已失效",
    "layout.sessionExpiredBody": "身份信息已过期，请重新登录。",
    "layout.accountMenu": "账号菜单",
    "login.showcaseTitle": "总知管理平台",
    "login.showcaseSubtitle": "Bossknow Management Platform",
    "login.username": "账号",
    "login.password": "密码",
    "login.captcha": "验证码",
    "login.enterUsername": "请输入账号",
    "login.enterPassword": "请输入密码",
    "login.enterCaptcha": "请输入验证码",
    "login.refreshCaptcha": "点击刷新验证码",
    "login.refreshingCaptcha": "验证码刷新中",
    "login.login": "登录",
    "login.loggingIn": "登录中...",
    "login.captchaLoading": "验证码加载中...",
    "login.captchaFailed": "验证码加载失败",
    "login.captchaIncorrect": "验证码错误，请重新输入",
    "login.credentialIncorrect": "账号或密码不正确",
    "login.failed": "登录失败，请稍后重试",
    "login.usernameRequired": "账号不能为空，请输入5-32位，可包含字母、数字、点、下划线、@、短横线",
    "login.usernameInvalid": "账号格式错误，请输入5-32位，可包含字母、数字、点、下划线、@、短横线",
    "login.passwordRequired": "密码不能为空，请输入6-18位并包含字母、数字、符号",
    "login.passwordInvalid": "密码格式错误，请输入6-18位并包含字母、数字、符号",
    "login.captchaRequired": "验证码不能为空，只能输入数字",
    "login.captchaInvalid": "验证码格式错误，只能输入数字",
    "forms.title": "表单列表",
    "forms.createForm": "创建表单",
    "forms.editForm": "编辑表单",
    "forms.formTitle": "表单标题",
    "forms.date": "日期",
    "forms.datePlaceholder": "年 / 月 / 日",
    "forms.hint": "创建后会直接进入 Excel 式设计页，在表格型页面中维护表头和时间段。",
    "forms.submitCreate": "创建表单",
    "forms.submitSave": "保存表单",
    "forms.submitting": "提交中...",
    "forms.draft": "待发布",
    "forms.active": "进行中",
    "forms.status": "状态",
    "forms.updatedAt": "更新时间",
    "forms.actions": "操作",
    "forms.publish": "发布",
    "forms.close": "关闭",
    "forms.fill": "填写页",
    "forms.history": "历史记录",
    "forms.edit": "编辑",
    "forms.delete": "删除",
    "forms.design": "设计页",
    "forms.publishConfirm": "发布后，个人账号即可开始填写该表单。确认发布吗？",
    "forms.closeConfirm": "关闭后，该表单将进入历史表单，不能继续填写或修改填报。确认关闭吗？",
    "forms.deleteConfirm": "确认删除该表单吗？",
    "history.pageTitle": "历史表单",
    "history.listTitle": "历史列表",
    "history.recordsTitle": "表单记录",
    "history.searchPlaceholder": "按标题搜索表单",
    "history.search": "搜索",
    "history.reset": "重置",
    "history.viewRecords": "查看记录",
    "history.export": "导出",
    "history.reopen": "重新开启",
    "history.noHistory": "暂无历史表单",
    "history.note": "点击左侧卡片查看该表单的历史记录。",
    "history.prevPage": "上一页",
    "history.nextPage": "下一页",
    "history.pageInfo": "第 {page} / {totalPages} 页，共 {total} 条",
    "history.time": "时间",
    "history.submitter": "提交人",
    "history.team": "团队",
    "history.updatedAt": "更新时间",
    "history.content": "内容",
    "history.noRecords": "暂无记录",
    "history.selectPrompt": "请选择左侧表单查看历史记录。",
    "fill.heroTitleSuffix": "表单填写",
    "fill.currentStatus": "当前状态：{status}",
    "fill.sectionTitle": "填写表格",
    "fill.note": "灰色“已被其他账号占用”表示该时间段已经被其他账号填写，您无权查看内容。",
    "fill.occupiedByTeam": "已被{team}占用",
    "fill.timeSlot": "时间 / 空位",
    "fill.action": "操作",
    "fill.fill": "填写",
    "fill.edit": "编辑",
    "fill.changeSlot": "更换时间段",
    "fill.resume": "简表",
    "fill.delete": "删除",
    "fill.refreshStatus": "刷新状态",
    "fill.contentTitle": "填写内容",
    "fill.submit": "提交",
    "fill.submitting": "提交中...",
    "fill.deleteTitle": "确认删除",
    "fill.deleteBody": "确认删除这条填报记录吗？删除后该时间段会恢复为空闲状态。",
    "fill.deleteAction": "确认删除",
    "fill.deleting": "删除中...",
    "fill.moveTitle": "更换时间段",
    "fill.currentSlot": "当前时间段",
    "fill.newSlot": "新的时间段",
    "fill.selectSlot": "请选择空余时间段",
    "fill.noSlot": "当前没有可更换的空余时间段。",
    "fill.confirmMove": "确认更换",
    "fill.moving": "确认更换中...",
    "fill.documentTitle": "简表管理",
    "fill.currentRecord": "当前记录",
    "fill.noContent": "暂无填写内容",
    "document.upload": "上传简表",
    "document.uploading": "上传中...",
    "document.generateBilingual": "生成中英双语简表",
    "document.empty": "暂无简表文件",
    "document.preview": "预览",
    "document.translatePreview": "翻译预览",
    "document.editBilingual": "编辑双语",
    "document.download": "下载",
    "document.delete": "删除",
    "document.previewTitle": "简表预览",
    "document.translateTitle": "翻译预览",
    "document.originalPreview": "原文预览",
    "document.englishPreview": "英文预览",
    "document.editorTitle": "编辑双语简表",
    "document.cn": "中文",
    "document.en": "English",
    "document.save": "保存",
    "document.saving": "保存中...",
    "document.loadFailed": "加载文档失败",
    "document.uploadFailed": "上传失败",
    "document.previewFailed": "预览失败",
    "document.translateFailed": "翻译预览失败",
    "document.needOriginalDocx": "请先上传中文 DOCX 简表文件，或先在线填写简表",
    "document.generateConfirm": "将调用 AI 生成中英双语简表，可能需要几十秒。\n确认生成吗？",
    "document.generateFailed": "生成双语简表失败",
    "document.deleteConfirm": "确认删除该简表文件吗？",
    "document.deleteFailed": "删除失败",
    "document.editorLoadFailed": "加载双语编辑器失败",
    "document.editorSaveFailed": "保存失败",
    "document.workExperience": "工作经历 {index}",
    "document.educationExperience": "教育经历 {index}",
    "document.companyZh": "公司中文",
    "document.companyEn": "公司英文",
    "document.positionZh": "职务中文",
    "document.positionEn": "职务英文",
    "document.schoolZh": "院校中文",
    "document.schoolEn": "院校英文",
    "document.courseZh": "课程中文",
    "document.courseEn": "课程英文",
    "document.degreeZh": "学位中文",
    "document.degreeEn": "学位英文",
    "designer.titleSuffix": "表格设计界面",
    "designer.dateMeta": "日期：{date} | 状态：{status}",
    "designer.hint": "先在第一行填写表头，再在第一列填写时间段。中间空白格不需要填写，那些位置留给个人账号后续填写。",
    "designer.tableTitle": "设计表格",
    "designer.addColumn": "新增列",
    "designer.removeColumn": "删除列",
    "designer.addRow": "新增行",
    "designer.removeRow": "删除行",
    "designer.previewFill": "预览填写页",
    "designer.saveDesign": "保存设计",
    "designer.saving": "保存中...",
    "designer.publish": "发布表单",
    "designer.publishing": "发布中...",
    "designer.time": "时间",
    "designer.action": "操作",
    "designer.emptyHeader": "空白表头{index}",
    "designer.emptySlot": "空白时间段",
    "designer.deleteRow": "删除行",
    "feedback.noData": "暂无数据",
    "feedback.loading": "加载中...",
    "role.super_admin": "超级管理员",
    "role.academic_admin": "教务账号",
    "role.team_admin": "团队账号",
    "role.personal": "个人账号",
    "role.interviewer": "面试官",
    "formStatus.draft": "草稿",
    "formStatus.active": "进行中",
    "formStatus.closed": "已结束",
    "entryStatus.empty": "空闲",
    "entryStatus.filled": "已填写",
    "entryStatus.occupied": "已被其他账号占用",
    "review.pending": "待定",
    "review.pass": "通过",
    "review.reject": "不通过",
  },
  "en-US": {
    "common.chinese": "中文",
    "common.english": "English",
    "common.cancel": "Cancel",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.select": "Select",
    "common.refresh": "Refresh",
    "common.save": "Save",
    "common.loading": "Loading...",
    "common.noData": "No data",
    "common.backToForms": "Back to Forms",
    "common.logout": "Log out",
    "common.changePassword": "Change Password",
    "common.relogin": "Sign In Again",
    "route.users": "Accounts",
    "route.teams": "Teams",
    "route.forms": "Forms",
    "route.formDesigner": "Form Designer",
    "route.formFill": "Form Fill",
    "route.history": "History",
    "route.documents": "Documents",
    "route.bilingualEditor": "Bilingual Resume Editor",
    "layout.brandTitle": "Dynamic Form Hub",
    "layout.brandSubtitle": "Admin Console",
    "layout.expandSidebar": "Expand sidebar",
    "layout.collapseSidebar": "Collapse sidebar",
    "layout.logoutConfirmTitle": "Confirm Logout",
    "layout.logoutConfirmBody": "Are you sure you want to log out? You will be returned to the login page.",
    "layout.logoutConfirmAction": "Log Out",
    "layout.passwordDialogTitle": "Change Password",
    "layout.passwordOld": "Current Password",
    "layout.passwordNew": "New Password",
    "layout.passwordConfirm": "Confirm New Password",
    "layout.passwordOldPlaceholder": "Enter your current password",
    "layout.passwordNewPlaceholder": "Enter your new password",
    "layout.passwordConfirmPlaceholder": "Enter the new password again",
    "layout.passwordSubmit": "Update Password",
    "layout.passwordSubmitting": "Submitting...",
    "layout.passwordChangeSuccess": "Password updated successfully. Please sign in again.",
    "layout.passwordOldRequired": "Current password is required.",
    "layout.passwordNewRequired": "New password is required. Use 6-18 characters with letters, numbers, and symbols.",
    "layout.passwordNewInvalid": "Invalid password format. Use 6-18 characters with letters, numbers, and symbols.",
    "layout.passwordConfirmRequired": "Please confirm the new password.",
    "layout.passwordConfirmMismatch": "The two new passwords do not match.",
    "layout.sessionExpiredTitle": "Session Expired",
    "layout.sessionExpiredBody": "Your identity has expired. Please sign in again.",
    "layout.accountMenu": "Account menu",
    "login.showcaseTitle": "Bossknow Admin Platform",
    "login.showcaseSubtitle": "Bossknow Management Platform",
    "login.username": "Username",
    "login.password": "Password",
    "login.captcha": "Captcha",
    "login.enterUsername": "Enter your username",
    "login.enterPassword": "Enter your password",
    "login.enterCaptcha": "Enter the captcha",
    "login.refreshCaptcha": "Click to refresh captcha",
    "login.refreshingCaptcha": "Refreshing captcha",
    "login.login": "Sign In",
    "login.loggingIn": "Signing in...",
    "login.captchaLoading": "Loading captcha...",
    "login.captchaFailed": "Failed to load captcha",
    "login.captchaIncorrect": "Incorrect captcha. Please try again.",
    "login.credentialIncorrect": "Incorrect username or password",
    "login.failed": "Sign-in failed. Please try again later.",
    "login.usernameRequired": "Username is required. Use 5-32 characters including letters, numbers, dot, underscore, @, or hyphen.",
    "login.usernameInvalid": "Invalid username format. Use 5-32 characters including letters, numbers, dot, underscore, @, or hyphen.",
    "login.passwordRequired": "Password is required. Use 6-18 characters with letters, numbers, and symbols.",
    "login.passwordInvalid": "Invalid password format. Use 6-18 characters with letters, numbers, and symbols.",
    "login.captchaRequired": "Captcha is required and must contain digits only.",
    "login.captchaInvalid": "Invalid captcha format. Digits only.",
    "forms.title": "Form List",
    "forms.createForm": "Create Form",
    "forms.editForm": "Edit Form",
    "forms.formTitle": "Form Title",
    "forms.date": "Date",
    "forms.datePlaceholder": "YYYY / MM / DD",
    "forms.hint": "After creation you will enter the spreadsheet-style designer to maintain headers and time slots.",
    "forms.submitCreate": "Create Form",
    "forms.submitSave": "Save Form",
    "forms.submitting": "Submitting...",
    "forms.draft": "Draft",
    "forms.active": "Active",
    "forms.status": "Status",
    "forms.updatedAt": "Updated At",
    "forms.actions": "Actions",
    "forms.publish": "Publish",
    "forms.close": "Close",
    "forms.fill": "Fill Page",
    "forms.history": "History",
    "forms.edit": "Edit",
    "forms.delete": "Delete",
    "forms.design": "Designer",
    "forms.publishConfirm": "Once published, personal accounts can start filling in this form. Continue?",
    "forms.closeConfirm": "After closing, this form will move to history and can no longer be filled or edited. Continue?",
    "forms.deleteConfirm": "Are you sure you want to delete this form?",
    "history.pageTitle": "History Forms",
    "history.listTitle": "History List",
    "history.recordsTitle": "Form Records",
    "history.searchPlaceholder": "Search forms by title",
    "history.search": "Search",
    "history.reset": "Reset",
    "history.viewRecords": "View Records",
    "history.export": "Export",
    "history.reopen": "Reopen",
    "history.noHistory": "No history forms",
    "history.note": "Click a card on the left to view historical records for that form.",
    "history.prevPage": "Previous",
    "history.nextPage": "Next",
    "history.pageInfo": "Page {page} / {totalPages}, {total} total",
    "history.time": "Time Slot",
    "history.submitter": "Submitted By",
    "history.team": "Team",
    "history.updatedAt": "Updated At",
    "history.content": "Content",
    "history.noRecords": "No records",
    "history.selectPrompt": "Select a form on the left to view its history records.",
    "fill.heroTitleSuffix": "Form Fill",
    "fill.currentStatus": "Current status: {status}",
    "fill.sectionTitle": "Fill Form",
    "fill.note": "Gray 'Occupied by another account' means this time slot has already been filled by another account and cannot be viewed.",
    "fill.occupiedByTeam": "Occupied by {team}",
    "fill.timeSlot": "Time / Slot",
    "fill.action": "Action",
    "fill.fill": "Fill",
    "fill.edit": "Edit",
    "fill.changeSlot": "Change Time Slot",
    "fill.resume": "Resume",
    "fill.delete": "Delete",
    "fill.refreshStatus": "Refresh Status",
    "fill.contentTitle": "Fill Content",
    "fill.submit": "Submit",
    "fill.submitting": "Submitting...",
    "fill.deleteTitle": "Confirm Delete",
    "fill.deleteBody": "Delete this submission record? The time slot will return to available status afterward.",
    "fill.deleteAction": "Delete Record",
    "fill.deleting": "Deleting...",
    "fill.moveTitle": "Change Time Slot",
    "fill.currentSlot": "Current Time Slot",
    "fill.newSlot": "New Time Slot",
    "fill.selectSlot": "Select an available slot",
    "fill.noSlot": "No available time slots can be selected right now.",
    "fill.confirmMove": "Confirm Change",
    "fill.moving": "Changing...",
    "fill.documentTitle": "Resume Manager",
    "fill.currentRecord": "Current Record",
    "fill.noContent": "No submitted content",
    "document.upload": "Upload Resume",
    "document.uploading": "Uploading...",
    "document.generateBilingual": "Generate Chinese-English Resume",
    "document.empty": "No resume files",
    "document.preview": "Preview",
    "document.translatePreview": "Translation Preview",
    "document.editBilingual": "Edit Bilingual",
    "document.download": "Download",
    "document.delete": "Delete",
    "document.previewTitle": "Resume Preview",
    "document.translateTitle": "Translation Preview",
    "document.originalPreview": "Original Preview",
    "document.englishPreview": "English Preview",
    "document.editorTitle": "Edit Bilingual Resume",
    "document.cn": "Chinese",
    "document.en": "English",
    "document.save": "Save",
    "document.saving": "Saving...",
    "document.loadFailed": "Failed to load documents",
    "document.uploadFailed": "Upload failed",
    "document.previewFailed": "Preview failed",
    "document.translateFailed": "Translation preview failed",
    "document.needOriginalDocx": "Please upload the Chinese DOCX resume file first, or fill in the online summary first",
    "document.generateConfirm": "AI will be used to generate a Chinese-English resume and it may take dozens of seconds.\nContinue?",
    "document.generateFailed": "Failed to generate the bilingual resume",
    "document.deleteConfirm": "Delete this resume file?",
    "document.deleteFailed": "Delete failed",
    "document.editorLoadFailed": "Failed to load the bilingual editor",
    "document.editorSaveFailed": "Save failed",
    "document.workExperience": "Work Experience {index}",
    "document.educationExperience": "Education Experience {index}",
    "document.companyZh": "Company (CN)",
    "document.companyEn": "Company (EN)",
    "document.positionZh": "Position (CN)",
    "document.positionEn": "Position (EN)",
    "document.schoolZh": "School (CN)",
    "document.schoolEn": "School (EN)",
    "document.courseZh": "Course (CN)",
    "document.courseEn": "Course (EN)",
    "document.degreeZh": "Degree (CN)",
    "document.degreeEn": "Degree (EN)",
    "designer.titleSuffix": "Form Designer",
    "designer.dateMeta": "Date: {date} | Status: {status}",
    "designer.hint": "Fill the header row first, then fill time slots in the first column. The empty middle cells are reserved for personal account submissions.",
    "designer.tableTitle": "Design Table",
    "designer.addColumn": "Add Column",
    "designer.removeColumn": "Remove Column",
    "designer.addRow": "Add Row",
    "designer.removeRow": "Remove Row",
    "designer.previewFill": "Preview Fill Page",
    "designer.saveDesign": "Save Design",
    "designer.saving": "Saving...",
    "designer.publish": "Publish Form",
    "designer.publishing": "Publishing...",
    "designer.time": "Time",
    "designer.action": "Action",
    "designer.emptyHeader": "Header {index}",
    "designer.emptySlot": "Time Slot",
    "designer.deleteRow": "Delete Row",
    "feedback.noData": "No data",
    "feedback.loading": "Loading...",
    "role.super_admin": "Super Admin",
    "role.academic_admin": "Academic Admin",
    "role.team_admin": "Team Admin",
    "role.personal": "Personal User",
    "role.interviewer": "Interviewer",
    "formStatus.draft": "Draft",
    "formStatus.active": "Active",
    "formStatus.closed": "Closed",
    "entryStatus.empty": "Available",
    "entryStatus.filled": "Submitted",
    "entryStatus.occupied": "Occupied by another account",
    "review.pending": "Pending",
    "review.pass": "Pass",
    "review.reject": "Reject",
  },
};

function readStoredLanguage() {
  if (typeof window === "undefined") {
    return DEFAULT_LANGUAGE;
  }

  const stored = window.localStorage.getItem(STORAGE_KEY);
  return stored === "en-US" ? "en-US" : DEFAULT_LANGUAGE;
}

export const currentUiLanguage = ref(readStoredLanguage());

export function t(key, params = {}) {
  const language = currentUiLanguage.value === "en-US" ? "en-US" : DEFAULT_LANGUAGE;
  const template = MESSAGES[language][key] || MESSAGES[DEFAULT_LANGUAGE][key] || key;
  return template.replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? `{${name}}`));
}

export function setUiLanguage(language) {
  const nextLanguage = language === "en-US" ? "en-US" : DEFAULT_LANGUAGE;
  currentUiLanguage.value = nextLanguage;

  if (typeof window !== "undefined") {
    window.localStorage.setItem(STORAGE_KEY, nextLanguage);
    window.dispatchEvent(
      new CustomEvent("app:ui-language-changed", {
        detail: { language: nextLanguage },
      })
    );
  }
}

export function toggleUiLanguage() {
  setUiLanguage(currentUiLanguage.value === "zh-CN" ? "en-US" : "zh-CN");
}

export function getUiLanguageLabel(language) {
  return language === "en-US" ? t("common.chinese") : t("common.english");
}

export function getRouteTitle(routeName) {
  const map = {
    users: "route.users",
    teams: "route.teams",
    forms: "route.forms",
    "form-designer": "route.formDesigner",
    "form-fill": "route.formFill",
    history: "route.history",
    documents: "route.documents",
    "bilingual-editor": "route.bilingualEditor",
  };
  return t(map[routeName] || "route.forms");
}
